packages:
  - software
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  "@platforma-sdk/model": ^1.29.2
  "@platforma-sdk/ui-vue": ^1.29.2
  "@platforma-sdk/workflow-tengo": ^4.4.5
  "@platforma-sdk/block-tools": ^2.5.36
  "@platforma-sdk/test": ^1.29.2
  "@platforma-sdk/tengo-builder": ^2.0.3
  "@platforma-sdk/package-builder": ^2.15.6
  "@platforma-sdk/eslint-config": ^1.0.3
  "@milaboratories/graph-maker": ^1.1.71
  
  "@platforma-open/milaboratories.software-ptransform": ^1.3.1  
  "@platforma-open/milaboratories.runenv-python-3": ^1.1.14
  
  "vue": ^3.5.13
  "vue-tsc": ^2.2.8
  
  "typescript": ~5.5.4
  "tsup": ~8.3.5
  "turbo": ^2.4.4
  "js-yaml": ^4.1.0

  "vite": ^6.2.2
  "vitest": ^2.1.8
  "@vitejs/plugin-vue": ^5.2.1

  "@changesets/cli": ^2.28.1
