packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  "@platforma-sdk/model": ^1.45.0
  "@platforma-sdk/ui-vue": ^1.45.5
  "@platforma-sdk/workflow-tengo": ^5.6.1
  "@platforma-sdk/block-tools": ^2.6.22
  "@platforma-sdk/test": ^1.45.11
  "@platforma-sdk/tengo-builder": ^2.3.3
  "@platforma-sdk/package-builder": ^3.10.6
  "@platforma-sdk/eslint-config": ^1.1.0
  "@milaboratories/graph-maker": ^1.1.174
  "@platforma-sdk/blocks-deps-updater": ^2.0.0
  
  "@platforma-open/milaboratories.runenv-python-3": ^1.4.8
  
  "vue": ^3.5.13
  "vue-tsc": ^2.2.8
  
  "typescript": ~5.5.4
  "tsup": ~8.3.5
  "turbo": ^2.4.4

  "vite": ^6.2.2
  "vitest": ^2.1.8
  "@vitejs/plugin-vue": ^5.2.1

  "@changesets/cli": ^2.28.1
