packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  "@platforma-sdk/model": ^1.42.22
  "@platforma-sdk/ui-vue": ^1.42.21
  "@platforma-sdk/workflow-tengo": ^5.0.3
  "@platforma-sdk/block-tools": ^2.5.83
  "@platforma-sdk/test": ^1.42.20
  "@platforma-sdk/tengo-builder": ^2.1.15
  "@platforma-sdk/package-builder": ^2.17.2
  "@platforma-sdk/eslint-config": ^1.0.3
  "@milaboratories/graph-maker": ^1.1.145
  
  "@platforma-open/milaboratories.runenv-python-3": ^1.1.16
  
  "vue": ^3.5.13
  "vue-tsc": ^2.2.8
  
  "typescript": ~5.5.4
  "tsup": ~8.3.5
  "turbo": ^2.4.4
  "js-yaml": ^4.1.0

  "vite": ^6.2.2
  "vitest": ^2.1.8
  "@vitejs/plugin-vue": ^5.2.1

  "@changesets/cli": ^2.28.1
