packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  # SDK packages - EXACT VERSIONS (no ^ or ~)
  '@milaboratories/ts-builder': 1.2.4
  '@milaboratories/ts-configs': 1.2.0
  '@platforma-sdk/workflow-tengo': 5.8.1
  '@platforma-sdk/model': 1.53.10
  '@platforma-sdk/ui-vue': 1.53.10
  '@platforma-sdk/tengo-builder': 2.4.14
  '@platforma-sdk/package-builder': 3.11.0
  '@platforma-sdk/block-tools': 2.6.42
  '@platforma-sdk/eslint-config': 1.2.0
  '@platforma-sdk/test': 1.53.10
  '@milaboratories/helpers': 1.13.0
  '@milaboratories/graph-maker': 1.1.222
  '@milaboratories/strings': 0.1.0

  # Common dependencies - can use ^ or ~
  'vue': ^3.5.24
  'typescript': ~5.6.3
  'turbo': ^2.6.3
  'vitest': ^4.0.7
  'shx': ^0.4.0
  'eslint': ^9.25.1
  '@changesets/cli': ^2.29.8

  # Block-specific dependencies
  "@platforma-open/milaboratories.runenv-python-3": ^1.7.5
